trigger: none

variables:
  dependencyCheckCache: false
  dependencyCheckBreak: false

stages:
  - template: 'templates/dependency_check.yaml'
    parameters:
      dependencyCheckCache: ${{ variables.dependencyCheckCache }}
      dependencyCheckBreak: ${{ variables.dependencyCheckBreak }}